language: ruby
rvm:
    - 2.4.0
    - 2.3.0
    - 2.2.0
    - 2.1.0
    - 2.0.0
    - 1.9.3
script:
    - bundle exec rspec

os:
    - linux
    - osx

notifications:
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/f7bca9192ed021143fea
        on_success: change
